### ISSUE TITLE
Border width

### ISSUE THREAD

**Issue by JaseElder** [Frezyx/group_button#106]
Hiya,

Fantastic package, thank you! 
One thing it's missing for me is the ability to specify the width of the button border. I've had to use a buttonBuilder to recreate all the other properties of a default GroupButton, but add the border width. Because of this, I lose the InkWell type splash effect.

**Comment by jenyang2** [comment]
How did you add the border width?

**Comment by JaseElder** [comment]
Fixed in 5.4.0
