### ISSUE TITLE
selectedBorderColor not working

### ISSUE THREAD

**Issue by Cyanoptilas** [Frezyx/group_button#11]
selectedBorderColor, unselectedBorderColor are not working. would you check it?

**Comment by SangRyeol-Yun** [comment]
I have the same problem. 
I want to know why.

**Comment by Frezyx** [comment]
I have released 2.1.2 version of the package which resolves this problem.
The version is now available at [pub.dev](https://pub.dev/packages/group_button)

Thank you for noticing it ❤️
