### ISSUE TITLE
When isRadio is true it starts with first button selected

### ISSUE THREAD

**Issue by roberto77mi** [Frezyx/group_button#12]
When I user isRadio=true I expect the options to be rendered with all button unselected. That would match how radio buttons work in HTML for example.

Right now, the first option is selected. In the example below, button A is selected automatically.

```
GroupButton(
            isRadio: true,
            spacing: 10,
            onSelected: (index, isSelected) => setState(
                () => choiceSelectionOutput = widget.optionsOutputText[index]),
            buttons: ["A","B", "C"]
        )
```

**Comment by Frezyx** [comment]
Hello @roberto77mi 👋🏻 

Thank you for this issue !
I create this functionality [in this pr](https://github.com/Frezyx/group_button/pull/16)

**Comment by Frezyx** [comment]
Now your example will work according to the principle that you described.

**Comment by ramith-ascentic** [comment]
Hi @Frezyx ,

I'm using the latest version of the plugin, but the functionality OP suggested is still not available for me.

Here is an example :

```
GroupButton(
  isRadio: true,
  spacing: 10,
  onSelected: (index, isSelected) => print('$index button is selected'),
  buttons: ["Male", "Female"],
),
```

I want both radio buttons (Male and Female) to be in unselected state when it's first rendered, until user selects an option. Am I missing anything here?

**Comment by Frezyx** [comment]
Hello @ramith-ascentic 👋🏻 
I do not published update with this functionality. 
I will write you about it.

**Comment by Frezyx** [comment]
Now i publish this changes to pub.dev. 
Update package version to 2.1.0 and see changes.

Have a good day !

**Comment by ramith-ascentic** [comment]
Awesome! Thanks for the update, works great!

**Comment by SalahAdDin** [comment]
I don't know why, but i still have this bug:
![image](https://user-images.githubusercontent.com/5034215/121069964-c8c1b980-c7d6-11eb-962e-3808909d2e49.png)

**Comment by SalahAdDin** [comment]
@Frezyx More debbugging here:
![image](https://user-images.githubusercontent.com/5034215/125977859-56a4df66-4e90-4358-a856-f75e0a655f12.png)

**Comment by SalahAdDin** [comment]
And it comes because https://github.com/Frezyx/group_button/blob/master/lib/src/group_button_body.dart#L60 selected index is always 0.

**Comment by SalahAdDin** [comment]
@Frezyx And it is fixed by https://github.com/Frezyx/group_button/pull/38.
