### ISSUE TITLE
"Old school" style.

### ISSUE THREAD

**Issue by SalahAdDin** [Frezyx/group_button#18]
Hi, thanks for this good alternative that can fulfill our needs.

I'm working on reproduce this [questionary application](https://github.com/jlaskowska/questionnaires), and I'm using this package as an alternative to `grouped_buttons`.

I would like to know if it is possible to get the oldschool style for checkbox(box) and radio buttons whit this package.

is there any way to do it with the current state of the package? Does it require a new feature?

Thank you very much.

**Comment by Frezyx** [comment]
Hello @SalahAdDin ✋🏻 

Until this moment, I had not thought about such functionality. But, in general, this is worth doing.
Now the buttons are customized. But not all users have enough.

**Comment by Frezyx** [comment]
It will be great if you suggest your own version of this functionality.

**Comment by SalahAdDin** [comment]
Ok, let me see what can i do. Thanks.

**Comment by Frezyx** [comment]
Hello @SalahAdDin !
This feature is available from 4.6.0 package [release](https://github.com/Frezyx/group_button/releases/tag/4.6.0)
You can use **buttonBuilder** or **buttonIndexedBuilder**
See more [here](https://github.com/Frezyx/group_button/blob/master/example/lib/examples/button_builder_example/example.dart)
