### ISSUE TITLE
SelectedButtons is not getting the correct selected button

### ISSUE THREAD

**Issue by SalahAdDin** [Frezyx/group_button#20]
I'm trying to make a form using this package and **Riverpod**.

Right now i'm trying to keep the button selected between different groups, but it does not:
![image](https://user-images.githubusercontent.com/5034215/115437286-a9fe6800-a214-11eb-981b-ab22dee23d40.png)
As you can see, both different questions can have different values, and they are saved, but when i try to keep each one for each question, both widgets keeps the same selected value:
![Record_player_20210420201527](https://user-images.githubusercontent.com/5034215/115437731-390b8000-a215-11eb-85d0-f040cf79c16b.gif)
It seems to keep the same index ever, as if always it would be the same widget, what is we don't want.

**Comment by SalahAdDin** [comment]
@Frezyx 
could it be related to [this](https://github.com/Frezyx/group_button/issues/12)?

**Comment by SalahAdDin** [comment]
@Frezyx 
could it be related to [this](https://github.com/Frezyx/group_button/issues/12)?

**Comment by SalahAdDin** [comment]
Well, it seems not been working yet. with **int** index too.

**Comment by Frezyx** [comment]
If you need to keep the current button layout, you can store the state in the Riverpod and send it to the widget.
Naturally, the values ​​will be reset when the widgets are rebuilt, as in your example.

**Comment by SalahAdDin** [comment]
> If you need to keep the current button layout, you can store the state in the Riverpod and send it to the widget.
> Naturally, the values ​​will be reset when the widgets are rebuilt, as in your example.

It does keep the same state across every question of the same type: right now it keep the same `selectedButton` across all radio buttons.

For instance, the first question has to answers, the second one has five answers, when i click the second answer in the first question(selected index will be 0), in the next question, also radio button, the selected button will be the selected on the last button, if we click on the second anwer (index will be 1) and we come back to the last question, or to the next question, selected answers will be those with index 1:
![Record_select-area_20210602143111](https://user-images.githubusercontent.com/5034215/120473268-84d24d00-c3af-11eb-878d-bc5e29803587.gif)
Also, if you see, radio button always render the first option at the beginning (without being selected).

The code for the widget is:
```dart
class QuestionWidget extends HookWidget {
  QuestionWidget({required this.surveyID});

  final String surveyID;

  final _shortAnswerValidator = MultiValidator([
    RequiredValidator(errorText: 'Bu soruya cevap vermelisiniz.'),
    MinLengthValidator(15, errorText: 'Bu cevap çok kısa'),
    MaxLengthValidator(50, errorText: 'Bu cevap çok uzun.')
  ]);

  final _longAnswerValidator = MultiValidator([
    RequiredValidator(errorText: 'Bu soruya cevap vermelisiniz.'),
    MinLengthValidator(50, errorText: 'Bu cevap çok kısa'),
    MaxLengthValidator(150, errorText: 'Bu cevap çok uzun.')
  ]);

  // QuestionWidget({Key? key, required this.question}) : super(key: key);

  Widget _renderInput(
      {required Question question, required SurveyNotifier surveyNotifier}) {
    Widget answerWidget;
    switch (question.type) {
      case QuestionType.OPEN_SHORT:
        answerWidget = TextFormField(
          // controller: _,
          validator: _shortAnswerValidator,
          decoration: const InputDecoration(
            hintText: "Cevabı buraya yazınız...",
          ),
        );
        break;
      case QuestionType.OPEN_LONG:
        answerWidget = TextFormField(
          // controller: _,
          validator: _longAnswerValidator,
          decoration: const InputDecoration(
            hintText: "Cevabı buraya yazınız...",
          ),
          keyboardType: TextInputType.multiline,
          maxLines: 8,
          maxLength: 1000,
        );
        break;
      case QuestionType.SINGLE:
        final List<String> buttons = question.answer!.split(",");
        final String selectedButton =
            surveyNotifier.answers[question.id]?.answer ?? '';
        print(Colorize(
                "Answer: $selectedButton, Index: ${buttons.indexOf(selectedButton).toInt()}")
            .lightBlue());
        answerWidget = GroupButton(
          spacing: 10,
          buttons: buttons,
          onSelected: (index, isSelected) => surveyNotifier.answerQuestion(
              questionId: question.id,
              answer: buttons[index],
              statement: question.statement),
          direction: Axis.vertical,
          selectedButton: selectedButton != ''
              ? buttons.indexOf(selectedButton).toInt()
              : null,
        );
        break;
      case QuestionType.MULTIPLE:
        final List<String> buttons = question.answer!.split(",");
        final String selectedButtons =
            surveyNotifier.answers[question.id]?.answer ?? '';
        answerWidget = GroupButton(
          spacing: 10,
          buttons: buttons,
          onSelected: (index, isSelected) {
            final String rawCurrentAnswer =
                surveyNotifier.answers[question.id]?.answer ?? '';
            final List<String> currentAnswer =
                rawCurrentAnswer != '' ? rawCurrentAnswer.split(",") : [];
            // TODO: if currentAnswer left empty, remove the answer
            if (isSelected) {
              currentAnswer.add(buttons[index]);
            } else {
              currentAnswer.remove(buttons[index]);
            }
            surveyNotifier.answerQuestion(
                questionId: question.id,
                answer: currentAnswer.join(","),
                statement: question.statement);
          },
          direction: Axis.vertical,
          isRadio: false,
          selectedButtons: selectedButtons != ''
              ? buttons.map((value) => buttons.indexOf(value).toInt()).toList()
              : null,
        );
        break;
      case QuestionType.BOOL:
        final List<String> buttons = ['Yanlış', 'Doğru'];
        // TODO: Keep it as a question state(question answer), at least for local
        // TODO: This keeps always the same selected option in radio buttons, but not in checkbox
        final String selectedButton =
            surveyNotifier.answers[question.id]?.answer ?? '';
        print(Colorize(
                "Answer: $selectedButton, Index: ${buttons.indexOf(selectedButton).toInt()}")
            .lightBlue());
        answerWidget = GroupButton(
          spacing: 10,
          buttons: buttons,
          selectedButton: selectedButton != ''
              ? buttons.indexOf(selectedButton).toInt()
              : null,
          onSelected: (index, isSelected) => surveyNotifier.answerQuestion(
              questionId: question.id,
              answer: buttons[index],
              statement: question.statement),
          direction: Axis.vertical,
        );
        break;
      default:
        // TODO: any better option?
        answerWidget = Container();
        break;
    }
    return answerWidget;
  }

  @override
  Widget build(BuildContext context) {
    final surveyNotifier =
        useProvider(surveyNotifierProvider(surveyID).notifier);
    final questionEntity = useProvider(questionEntityProvider);
    final _question = questionEntity.state;
    if (_question == null) {
      return Column(
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.only(left: 30.0, right: 8.0),
            child: Text(
              'Bu anketinin soruları hala yok!',
              style:
                  Theme.of(context).textTheme.bodyText1!.copyWith(fontSize: 25),
            ),
          ),
        ],
      );
    }
    return Column(
      children: <Widget>[
        Padding(
          padding: const EdgeInsets.only(left: 30.0, right: 8.0),
          child: Text(
            _question.statement,
            style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w700),
            textAlign: TextAlign.left,
          ),
        ),
        const SizedBox(height: 24),
        _renderInput(
          question: _question,
          surveyNotifier: surveyNotifier,
        ),
      ],
    );
  }
}
```

The question entity comes from a _Riverpod_ provider and the _group buttons_ are rendered based on the question type.

When we debug it at changing over question widgets, everything seems ok, but the rendering is always wrong:
Initial State:
![image](https://user-images.githubusercontent.com/5034215/120473997-52751f80-c3b0-11eb-9bc9-0268dfde71e4.png)
First answer and next question:
![image](https://user-images.githubusercontent.com/5034215/120474144-83edeb00-c3b0-11eb-9a1d-43c2dbead4c9.png)
Coming back to first question:
![image](https://user-images.githubusercontent.com/5034215/120474279-aed83f00-c3b0-11eb-90ee-f852f4285e88.png)

The widget itself contains the correct selected button, but as the next question's seletec button index is four, the widget does not render the selected button correctly.

Why?

**Comment by SalahAdDin** [comment]
Using `autoDispose` at providers does not solve the problem.

**Comment by Frezyx** [comment]
I don't know why it doesn't work in your case
But I didn't get lazy and create [example with using provider as state - manager](https://github.com/Frezyx/group_button/tree/master/example/lib/examples/provider_example)

I ask you to read how it works and correct your application code.
For manage state of different GroupButton widgets.

Here mov with this example

https://user-images.githubusercontent.com/40857927/120866628-d21a0e80-c5a9-11eb-8c98-70c98bd3f389.mp4

**Comment by SalahAdDin** [comment]
> I don't know why it doesn't work in your case
> But I didn't get lazy and create [example with using provider as state - manager](https://github.com/Frezyx/group_button/tree/master/example/lib/examples/provider_example)
> 
> I ask you to read how it works and correct your application code.
> For manage state of different GroupButton widgets.
> 
> Here mov with this example
> 
>  Screenrecorder-2021-06-05-02-38-53-35.mp4

It seems to be realted to use a `StateProvider` to control the questions' flow; we replaced it by a `PageView` and every question as its child, and it work like a sharm.

Thank you.
