### ISSUE TITLE
scrollable button group list 

### ISSUE THREAD

**Issue by YouSour** [Frezyx/group_button#21]
hi, do you have any plan update this package that allow user can scroll  button group list ?

**Comment by SalahAdDin** [comment]
@YouSour I think this package is not maintained anymore, isn't it @Frezyx ?

**Comment by YouSour** [comment]
@Frezyx i'm not sure , but i see source code just updated

**Comment by Frezyx** [comment]
Hello @YouSour !

Are you try to use GroupButton wrapping in ListView widget ?

**Comment by YouSour** [comment]
@Frezyx yeah , what i want it scrollable 😄

**Comment by Frezyx** [comment]
Hello @YouSour ✋🏻 
I release [3.0.0](https://github.com/Frezyx/group_button/releases/tag/3.0.0) version of package. In this version you can use different grouping types.
This functionality can help you with your problem.

Check extended example [here](https://github.com/Frezyx/group_button/tree/master/example/lib/examples/extended_example)

**Comment by YouSour** [comment]
@Frezyx ok, thank you so much, you can close this issue , bro,  i 'll try it on my project , any problem i will report to u 😄
