### ISSUE TITLE
selectedButtons 

### ISSUE THREAD

**Issue by kamithL** [Frezyx/group_button#26]
Hi ,we cant run without any button selected ?
 i need when page load after no selection any buttons

**Comment by SalahAdDin** [comment]
@kamithL I could be related to https://github.com/Frezyx/group_button/issues/12

**Comment by Frezyx** [comment]
Hello @SalahAdDin and @kamithL ✋🏻 
Now I have a lot of work to do. 
Therefore, features take a very long time to reach my open source projects.

I will be very grateful to you if you can implement the functionality yourself.
It will be useful for you and me.
