### ISSUE TITLE
Centering button on vertical direction.

### ISSUE THREAD

**Issue by SalahAdDin** [Frezyx/group_button#30]
Hello again,

This package is so good, we got used to it and we like to work with it.

We just have a single suggestion for styling:
![image](https://user-images.githubusercontent.com/5034215/121071666-e98b0e80-c7d8-11eb-9f87-fceedf22dbc2.png)

As you can see, in vertical direction not all buttons are properly centered, it would be great to have them centered by default, or optionally centered.

What do you think?

**Comment by Frezyx** [comment]
Hello @SalahAdDin ✋🏻 
I create **mainGroupAlignment** and **crossGroupAlignment** fields for solve this problem

Check more info in [release notes](https://github.com/Frezyx/group_button/blob/master/CHANGELOG.md)
