### ISSUE TITLE
PROPOSAL: Provide a GroupButtonOptions as an immutable class for configuration purpose

### ISSUE THREAD

**Issue by wer-mathurin** [Frezyx/group_button#47]
@Frezyx 

Adding an object like:
GroupButtonOptions(TextAlign, Padding, etc...)

This will make easier to add option(s) in the future and make the source code more readable.
So we pass one object throw the classes hierarchy instead of duplicating variable across classes, this will make the maintenance of the library more easy.

**Comment by gnassro** [comment]
i think this issue is fixed https://github.com/Frezyx/group_button/pull/68

**Comment by Frezyx** [comment]
Hello @wer-mathurin !
I implement it in https://github.com/Frezyx/group_button/pull/66
