### ISSUE TITLE
Whether to consider adding the maximum number of selections

### ISSUE THREAD

**Issue by 979881765** [Frezyx/group_button#49]

**Comment by rockstarvibu** [comment]
please add maximum no of selection. it is must needed feature

**Comment by Frezyx** [comment]
Hello @rockstarvibu ! Now there is a working week and I can't devote time to this issue. If someone is ready to do this in this week, I will post a new version. In another case, I won't be able to add it until the weekend.

**Comment by Frezyx** [comment]
@rockstarvibu @979881765 this feature is available in 4.7.0
Thanks for @gnassro

**Comment by Frezyx** [comment]
https://pub.dev/packages/group_button/versions
