### ISSUE TITLE
Removing onPressed Shadow

### ISSUE THREAD

**Issue by Jayvd** [Frezyx/group_button#5]
How do we remove the shadow appears when the button is being pressed?

I tried this but it doesn't work
`selectedShadow: <BoxShadow>[
                      BoxShadow(color: Colors.transparent)
                    ],
unselectedShadow: <BoxShadow>[
                      BoxShadow(color: Colors.transparent)
                    ],`

**Comment by Frezyx** [comment]
Hello @Jayvd ! 
This issue is solved by using ElevatedButton. 

Thank you for this issue 👍🏻
