### ISSUE TITLE
Cannot dynamically change the selected button

### ISSUE THREAD

**Issue by darker-dubai** [Frezyx/group_button#51]
GroupButton(
                    spacing: 10.w,
                    isRadio: true,
                    buttons: _tabValues,
                    onSelected: _onTabbarTap,
                    ### selectedButton: _tabbarIndex,
)

setState(() {
          _tabbarIndex = index;
        });

It's doesn't work!, How can I do?

**Comment by Frezyx** [comment]
Hello!
Now you can work with GroupButtonController in [new 4.0.0 version](https://github.com/Frezyx/group_button/releases/tag/4.0.0)
