### ISSUE TITLE
Adjust the Height and Width of the Button

### ISSUE THREAD

**Issue by Jayvd** [Frezyx/group_button#6]
Is it possible to adjust the width and height of the buttons? I couldn't find any property for that

**Comment by Frezyx** [comment]
Hello @Jayvd !
Thank you for this issue. This functionality added in new version that available in [pub.dev](https://pub.dev/packages/group_button).

<br>

![Screenshot 2021-03-03 at 10 50 24](https://user-images.githubusercontent.com/40857927/109760305-442c3180-7c10-11eb-8c03-1b11eee3d52d.png)
