### ISSUE TITLE
How to have buttons take up available parent width

### ISSUE THREAD

**Issue by banderberg** [Frezyx/group_button#62]
This is more of a question - but I am placing a GroupButton with two buttons in an Expanded inside of a row, and I expected them to automatically fill out the available width of the Expanded widget but they don't.  

How can I do this?  I don't want to have to explicitly set the button widths.

**Comment by Frezyx** [comment]
Hello @banderberg !
Can you provide some code of your usage experience ?
Not all app, your screen or widget only 😄

**Comment by banderberg** [comment]
I just wrapped in a LayoutBuilder and set the button width to constraints.maxWidth / 2
