### ISSUE TITLE
Adding boolean option to radion button to make selected button can be unselected

### ISSUE THREAD

**Issue by gnassro** [Frezyx/group_button#64]
So my proposal is, if we can add an boolean option named like `'isRadioCanBeUnselected'`:

- if it true

the selected radio button can be unselected if it tapped again, so the event `onSelected: (index, isSelected)` will return `isSelected = false` if the radio button unselected.
What do you think ?

**Comment by Frezyx** [comment]
Hello @gnassro ! 
Yeah, that sounds cool.
