### ISSUE TITLE
Question: Color code buttons based on their value

### ISSUE THREAD

**Issue by asmith26** [Frezyx/group_button#74]
Hi there,

I'm hoping to color code my buttons based on their value, e.g. 

![image](https://user-images.githubusercontent.com/6988036/157864451-317518cc-0885-46e6-b31f-074955a6cb68.png)

Is this possible/is there any example code you can point me to?

Thanks for any help, and for this amazing lib! :)

**Comment by gnassro** [comment]
> Hi there,
> 
> I'm hoping to color code my buttons based on their value, e.g.
> 
> ![image](https://user-images.githubusercontent.com/6988036/157864451-317518cc-0885-46e6-b31f-074955a6cb68.png)
> 
> Is this possible/is there any example code you can point me to?
> 
> Thanks for any help, and for this amazing lib! :)

yes you can customize your buttons based on button index with buttonBuilder (version 4.6.0)

```
GroupButton(
          isRadio: false,
          controller: controller,
          buttons: [
            '12:00',
            '13:00',
            '14:00'
          ],
          onSelected: (i, selected) => debugPrint('Button #$i $selected'),
          buttonBuilder: (selected, index, context) {  // <== this will help you
            if (selected) {
              return Text('Colored');
            }
            return Text('not Colored');
          },
        )
```

**Comment by asmith26** [comment]
Thank you very much for your guidance @gnassro, I got this to work:

```dart
  Widget buildButtons(isSelected, index) {
    final myCoolColors = const <int, Color>{
      1: Colors.red,
      2: Colors.yellow,
      3: Colors.green,
    };
    return CircleAvatar(
      backgroundColor: myCoolColors[index],
      radius: 60.0,
      child: CircleAvatar(
        child: Text(index.toString(),
            style: TextStyle(color: isSelected ? Colors.white : Colors.black)),
        backgroundColor: isSelected ? Colors.blue : Colors.white,
        radius: 50.0,
      ),
    );
  }

...
        GroupButton(
            buttons: ['1', '2', '3'],
            onSelected: (index, isSelected) => debugPrint('Button #$index $isSelected'),
            buttonBuilder: (isSelected, index, context) => buildButtons(isSelected, index)),
```
