### ISSUE TITLE
Question: Horizontal scrolling GroupButton (e.g. for creating "quick search buttons")

### ISSUE THREAD

**Issue by asmith26** [Frezyx/group_button#75]
I'm trying to add "quick search buttons" to my flutter app like (in red):

![image](https://user-images.githubusercontent.com/6988036/158018544-a3f85120-0cc1-46e1-8618-5d326b3a4ea5.png)

This packages looks great for the button part of this, but I'm struggling to make the GroupButton horizontal scrollable. I can achieve this using a `ListView.separated`, e.g. (from https://stackoverflow.com/a/71386591/5179470)
```dart
ListView.separated(
                itemCount: fruits.length,
                scrollDirection: Axis.horizontal,
                itemBuilder: (context, index) => FilterChip(
                  label: Text(fruits[index]),
                  selected: index == selectedIndex,
                  onSelected: (value) {
                    setState(() {
                      selectedIndex = index;
                    });
                  },
                ),
```

but I can't seem to get a GroupButton to work with this. This issue looks related: https://github.com/Frezyx/group_button/issues/21 (mentioning @YouSour in case they have got it to work).

Many thanks for any help, and for this amazing lib!! :)

**Comment by Frezyx** [comment]
Hello @asmith26 !
At this moment, you can't do US using ListView.builder() and the Group Button package.
The only solution I can offer for you - use ListView on top of GroupButton.

Simple example:
```dart
ListView(
          scrollDirection: Axis.horizontal,
          children: [
            GroupButton(
              controller: controller,
              options: GroupButtonOptions(
                groupingType: GroupingType.row,
              ),
              isRadio: false,
              buttons: List.generate(25, (i) => '${i + 1}'),
              onSelected: (i, selected) => debugPrint('Button #$i $selected'),
            ),
          ],
        ),
```

Here is result:
https://user-images.githubusercontent.com/40857927/158019659-cc380c72-02e6-4ea9-94e2-a7c254d8ef58.mov

**Comment by Frezyx** [comment]
Result:
https://user-images.githubusercontent.com/40857927/158019988-a07cda03-9e86-4b4d-a0c8-00d32b114310.mp4

**Comment by asmith26** [comment]
Thanks soooooooo much for your help @Frezyx, this works beautifully!!
