### ISSUE TITLE
Add ability to unselect a radio button by pressing it again (toggleable property)

### ISSUE THREAD

**Issue by asmith26** [Frezyx/group_button#76]
Flutter Radio Buttons have a [Toggleable](https://api.flutter.dev/flutter/material/Radio/toggleable.html) property, allowing a user to unselect it as required. 

I would love it this fantastic lib could support this. Many thanks for any help! :)

**Comment by gnassro** [comment]
> Flutter Radio Buttons have a [Toggleable](https://api.flutter.dev/flutter/material/Radio/toggleable.html) property, allowing a user to unselect it as required.
> 
> I would love it this fantastic lib could support this. Many thanks for any help! :)

in version 4.5 and above you can use this feature by setting `enableDeselect: true`

**Comment by asmith26** [comment]
Thank you soooooooo much @gnassro, this lib is **_amazing!!_**

Create a PR to update the doc if helpful: https://github.com/Frezyx/group_button/pull/77
