### ISSUE TITLE
why remove GroupButton.checkbox

### ISSUE THREAD

**Issue by wengxianxun** [Frezyx/group_button#94]
why remove GroupButton.checkbox

**Comment by Frezyx** [comment]
Hello @wengxianxun !
This factory constructor was used extremely rarely

**Comment by wengxianxun** [comment]
how to use checkbox now , thk

**Comment by wengxianxun** [comment]
@Frezyx

**Comment by Frezyx** [comment]
Make isRadio: false in GroupButton constructor
