### ISSUE TITLE
group_button_item.dart:91:9: Error: No named parameter with the name 'backgroundColor'.         backgroundColor: _getBackgroundColor(theme),         ^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by patrakaibalya** [Frezyx/group_button#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by murat-ti** [comment]
Hi, I have the same problem. Maintainer adviced to me upgrade Flutter version to 3.3.0, where as he said background attribute is supported. But if you are using older version of flutter you must change from 'background' to 'primary' and it will work.

**Comment by Frezyx** [comment]
I upload [5.2.1](https://pub.dev/packages/group_button/versions/5.2.1) version with compatibility of older versions of flutter
@murat-ti @patrakaibalya

**Comment by murat-ti** [comment]
Thank you Stanislav. I upgraded flutter after your advice and it worked)
